calculator:lib/bool.h lib/double.h lib/elem.h lib/file.h lib/func.h lib/gramCheck.h lib/plantTree.h lib/poly.h lib/status.h lib/str.h lib/tools.h lib/treeBasic.h lib/types.h main.c
	gcc -o calculator main.c -lm -leditline 
clean:
	rm -f calculator 
